name: ci-cd

on:
  push:
    branches: ["master"]

jobs:
  pre:
    name: build image, convert tar, github release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t ${{secrets.PROJECT_NAME}} .
      - name: Save image to tar
        run: |
          docker save -o ${{secrets.PROJECT_NAME}}.tar ${{secrets.PROJECT_NAME}}
          tar -tf ${{secrets.PROJECT_NAME}}.tar
      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        run: |
          gh release create v${{secrets.CURRENT_VER}} ${{secrets.PROJECT_NAME}}.tar --title "v${{secrets.CURRENT_VER}}" --notes "Release v${{secrets.CURRENT_VER}}" --latest

  deploy:
    needs: pre
    name: deploy image in remote vps
    runs-on: ubuntu-latest

    steps:
      - name: Login to vps and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.REMOTE_SSH_HOST}}
          username: ${{secrets.REMOTE_SSH_USER}}
          password: ${{ secrets.REMOTE_SSH_PW }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIR }}
            rm ${{secrets.PROJECT_NAME}}.tar
            gh release download v${{secrets.CURRENT_VER}} --repo ${{github.repository}} --pattern "${{secrets.PROJECT_NAME}}.tar"
            docker load -i ${{secrets.PROJECT_NAME}}.tar
            docker run -d -p 3020:3020 --env-file .env ${{secrets.PROJECT_NAME}}
