name: ci-cd

on:
  push:
    branches: ["master"]

jobs:
  pre:
    name: build image, convert tar, github release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build -t nodejs-simple-server .
      - name: Save image to tar
        run: |
          docker save -o nodejs-simple-server.tar nodejs-simple-server
          tar -tf nodejs-simple-server.tar
      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        run: |
          gh release create v1.0.0 nodejs-simple-server.tar --title "v1.0.0" --notes "Release v1.0.0" --latest

  init:
    needs: pre
    name: stop-remove container, remove image
    runs-on: ubuntu-latest

    steps:
      - name: stop-remove container, remove image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.REMOTE_SSH_HOST}}
          username: ${{secrets.REMOTE_SSH_USER}}
          password: ${{ secrets.REMOTE_SSH_PW }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIR }}
            docker rm -f nodejs-simple-server
            docker rmi nodejs-simple-server

  deploy:
    needs: init
    name: deploy image in remote vps
    runs-on: ubuntu-latest

    steps:
      - name: Login to vps and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.REMOTE_SSH_HOST}}
          username: ${{secrets.REMOTE_SSH_USER}}
          password: ${{ secrets.REMOTE_SSH_PW }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIR }}
            rm nodejs-simple-server.tar
            gh release download v1.0.0 --repo ${{github.repository}} --pattern "nodejs-simple-server.tar"
            docker load -i nodejs-simple-server.tar
            docker run -d -p 3020:3020 --env-file .env nodejs-simple-server
