name: ci-cd

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build -t nodejs-simple-server .

  tar:
    needs: build
    name: convert image to tar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Save image to tar
        run: |
          docker save -o nodejs-simple-server.tar nodejs-simple-server
          tar -tf nodejs-simple-server.tar

  release:
    needs: tar
    name: release tar to github release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        run: |
          gh release create v1.0.0 nodejs-simple-server.tar --title "v1.0.0" --notes "Release v1.0.0"

  deploy:
    needs: release
    name: deploy image in remote vps
    runs-on: ubuntu-latest

    steps:
      - name: Login to vps and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.REMOTE_SSH_HOST}}
          username: ${{secrets.REMOTE_SSH_USER}}
          password: ${{ secrets.REMOTE_SSH_PW }}
          port: 22
          script: |
            cd ${{ secrets.REMOTE_WORKING_DIR }}
            curl -L -H "Authorization: token ${{ secrets.TOKEN }}" -o nodejs-simple-server.tar https://github.com/${{ github.repository }}/releases/download/v1.0.0/nodejs-simple-server.tar
            docker load -i nodejs-simple-server.tar
            docker run -d --env-file .env nodejs-simple-server
